### PR TITLE
Upgrades and split into three OS versions

### PR DESCRIPTION
**Pull request by DieterHolz**

### CODE REVIEW

**Comment by FDelporte** [comment]
@DieterHolz you're fast ;-)

**Comment by FDelporte** [comment]
Shouldn't the crowpi example project be included in https://github.com/Pi4J/pi4j-os/tree/upgrade-jdk18-jfx18/crowpi/resources ?

**Comment by DieterHolz** [comment]
> Shouldn't the crowpi example project be included in https://github.com/Pi4J/pi4j-os/tree/upgrade-jdk18-jfx18/crowpi/resources ?

Yes, of course.

Will fix it.

**Comment by DieterHolz** [comment]
Now, after double-checking CrowPiOS, I'm not really sure what you mean with "Shouldn't the crowpi example project be included".

First, I assumed that "HelloFX" and "MinimalPi4J" is missing. But they are included.

**Comment by FDelporte** [comment]
This one: https://github.com/Pi4J/pi4j-example-crowpi

**Comment by DieterHolz** [comment]
My previous opinion was that we should push our students towards using their laptops as developer machine and the Pi for running the apps only.

Therefore I would not include the crowpi-example project in CrowPiOS.

If you really want to use it directly on Pi, it's only a single git clone away.

The READMEs of cropwpi-examples and Pi4J-OS needs to be adjusted, accordingly.

But maybe it's time to do things differently ....

**Comment by FDelporte** [comment]
> Therefore I would not include the crowpi-example project in CrowPiOS.

valid point!

**Review by FDelporte — APPROVED** [review]

**Pull request merged**
