### PR TITLE
Wallpaper script + instructions

### PR DESCRIPTION
**Pull request by FDelporte**
Related to #46

### CODE REVIEW

**Comment by DieterHolz** [comment]
I would prefer to have the wallpaper in fixed size and centered on screen.

pcmanfm --set-wallpaper wallpaper-out.png --wallpaper-mode=center

**Comment by FDelporte** [comment]
@DieterHolz do you mean with the info content placed on the center of the image?

**Comment by DieterHolz** [comment]
For example if you do

jbang GenerateWallpaperInfoImage.java wallpaper-1-1920x1080.png wallpaper-out.png 910 540    

pcmanfm --set-wallpaper wallpaper-out.png --wallpaper-mode=center

you can see what I mean. 

With that approach it should be possible to use the original pi4j logo without much of a margin and add the system information

**Comment by DieterHolz** [comment]
@FDelporte To get the wallpaper updated, it would be nice to get notified whenever some of the addresses has changed and call the wallpaper-script only then .

I'm not a Linux-expert, but it could be something like that:

[ip-change-notify.zip](https://github.com/user-attachments/files/17778518/ip-change-notify.zip)

If it's copied to /etc/NetworkManager/dispatcher.d and is executable, it should work.

**Comment by DieterHolz** [comment]
something like this:

image

**Comment by DieterHolz** [comment]
@FDelporte 
I've included the wallpaper as mentioned above here:

https://gitlab.fhnw.ch/ip_12_preparation/hellopi5/-/tree/329faabf8265eb1629d798f2c107e93a1c65bc8d/setup

It's installed during setup.sh.

image

**Review by eitch — APPROVED** [review]
looks good

**Pull request merged**
