### PR TITLE
Feature: Switch image architecture to aarch64

### PR DESCRIPTION
**Pull request by ppmathis**
This PR changes the default image architecture from armhf (32-bit) to aarch64 (64-bit) for both CrowPi and Picade. This is the modern approach for Raspberry Pi devices and could potentially resolve some outstanding issues with Gluon X11/DRM.

### CODE REVIEW

**Comment by FDelporte** [comment]
Wow, that would be a big change! 64bit for the win ;-)

**Comment by DieterHolz** [comment]
Looks promising (except the known issues).

The new RaspPiFX-Template is running. That's great.

Some remarks:
- we should upgrade to pi4J 2.0.1
- audio test in PureJavaFX could be enabled (doesn't work properly, yet)
- There's a new Java Version. Should we switch to 'Temurin 11.0.13' ? Or even Java 17?
- JavaFX 17.0.2-ea does include DRM (but doesn't work). Should we use it instead of 17.0.1?

The overall question: Should we switch to RaspPi 64? There are JavaFX-problems on both 32 and on 64, although they are different.

**Comment by ppmathis** [comment]
My two cents:

> we should upgrade to pi4J 2.0.1

Sounds good - implemented as ac6260230d2fc397f9893d4f37e513126ffb2e4e. Also upgraded `maven-dependency-plugin`, implemented as 65b84720d0de8404bff62de0a8ac5a9df77c6d23.

> audio test in PureJavaFX could be enabled (doesn't work properly, yet)

So after understanding that the remaining issue is the background music which stops after a second, I investigated a little further and it turns out that JavaFX requires a `javafx.scene.media.MediaView` to be present, otherwise the `javafx.scene.media.MediaPlayer` instance gets garbage-collected and will be automatically stopped after a short time. This can also be found in [this bug](https://bugs.openjdk.java.net/browse/JDK-8138754).

Implemented as 069711a0cb50cf34383d15aed59c11b1214f53db.

> There's a new Java Version. Should we switch to 'Temurin 11.0.13' ? Or even Java 17?

I would either stick to OpenJDK 11 or OpenJDK 17, as those are the most official versions for most Linux systems and shipped via the system package manager, also guaranteeing easy security updates when users run `apt update && apt upgrade` on our system images. I tried a manual upgrade to OpenJDK 17 and as expected I was still able to run bytecode produced by OpenJDK 11, so I see no reason not to upgrade to the latest LTS. After all, this PR also lifts the Debian release from Buster to Bullseye, so it makes sense to update everything else as well.

Implemented as bc526433861c05a0a68e8aad6c12ff810df0121b.

> JavaFX 17.0.2-ea does include DRM (but doesn't work). Should we use it instead of 17.0.1?

I am still not quite sure what this is supposed to mean, when filtering on the [Gluon download page](https://gluonhq.com/products/javafx/) by `17.0.1 [LTS] - Linux - aarch64` there are both `SDK` (not bundled with DRM) as well as `Monocle SDK` (bundled with DRM). The `17.0.2-ea+1` version only contains a single `SDK` download, which comes bundled with DRM and is equivalent (in terms of files / contents, aside from version) to the `Monocle SDK`. So I see no reason to use the early access version? Both versions unfortunately struggle with the `0 screens detected` bug.

I noticed though that my previous commit did not download the Monocle SDK before, so this has been fixed as part of 0711a146fa49e7401e5818edd7edc5f35aa990a2.

> Should we change the password of pi4J-Spot to 'MayTheSourceBeWithYou!' ?

I don't have a personal favorite myself, so if you should prefer this one, this can surely be changed.

> Should we switch to RaspPi 64? There are JavaFX-problems on both 32 and on 64, although they are different.

I would propose moving to 64-bit for the `crowpi` flavor, optionally introducing a second flavor called `crowpi32` if there is any need for that. Then 64-bit would be the recommended default and 32-bit could be an optional fallback. The disadvantage of having two flavors is obviously a bit more effort in terms of testing and support, as the two versions might differ. Opinions?

**FYI:** The build currently fails due to an unrelated issue, seems like the system repositories are currently in a semi-broken state for the VLC packages:

```
    arm.raspios: The following packages have unmet dependencies:
    arm.raspios:  vlc-bin : Depends: libvlc-bin (= 3.0.16-1+rpi1+rpt1) but 3.0.16-1+rpi1+rpt2 is to be installed
    arm.raspios:  vlc-plugin-skins2 : Depends: vlc-plugin-qt (= 3.0.16-1+rpi1+rpt2) but 3.0.16-1+rpi1+rpt1 is to be installed
```

Will try a rebuild later on, this is something that the maintainers of these packages have to fix and also happens on an already installed system.

**Comment by DieterHolz** [comment]
OK. 

Then let's go for Raspi 64 (optional 32 later, maybe never), JDK 17, JavaFX 17.0.1, MayTheSourceBeWithYou!.

All the known JavaFX-bugs "enabled". Gluon can use our Image to reproduce them easily.

**Review by FDelporte — APPROVED** [review]
Nice work! I'm ready to move all my PIs to 64bit ;-)

**Comment by ppmathis** [comment]
This should be ready for review now, some tests on my side confirmed that everything except DRM (due to the "0 screens returned" issue) works properly, including the JavaFX demo project on X11 with background music and sound. I also updated the README and changed the WiFI password to `MayTheSourceBeWithYou!`.

So everything seems to work smoothly on the CrowPi with a Raspberry Pi 3B+. Due to lack of hardware I can't provide any feedback about Raspberry Pi 4 or the Picade itself, so this is something that would be worth checking out as well.

I created a Git tag `0.1.0` for the currently available version in the `main` branch, so that even after merging this PR the default download link will still point towards the 32-bit version with working DRM. That way we can flexibly decide when we want to switch to the 64-bit version, ideally once the DRM issue has been fixed by Gluon.

**Comment by DieterHolz** [comment]
I just tested CrowPi-Image on a Pi4. 

"Everything" seems to work. It's the first time ever, that the audio-examples of "HelloFX" is working.

I also tested our brand-new RaspiFX-Template-Project. Works as well.

 :-)  :-)  :-) :-)

Tomorrow I will test PicadeImage. 

I would suggest to merge this PR right now.

**Pull request merged**
